export const PRODUCT_ADD = 'PRODUCT_ADD';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE';
export const CUSTOMER_ADD = 'CUSTOMER_ADD';
export const CUSTOMER_DELETE = 'CUSTOMER_DELETE';
export const CUSTOMER_UPDATE = 'CUSTOMER_UPDATE';
export const CUSTOMER_SELECT = 'CUSTOMER_SELECT';
